### ISSUE TITLE
CV not up to date

### ISSUE THREAD

**Issue by martinbjeldbak** [Obeyed/obeid.dk#1]
Please update what you're up to, so the rest of us can follow along!

**Comment by Obeyed** [comment]
Thank you for your feedback. I'm thinking of doing this over. Have a nice day.

**Comment by martinbjeldbak** [comment]
You too, friend

Mvh.
Martin Bjeldbak Madsen
martinbmadsen@gmail.com
 <mailto:martinbmadsen@gmail.com>
